---
- name: Create navidrome user
  ansible.builtin.user:
    name: "{{ navidrome_container_user }}"
    shell: /sbin/nologin
    create_home: true
    state: present
  become: true

- name: Get created user metadata
  ansible.builtin.getent:
    database: passwd
    key: "{{ navidrome_container_user }}"

- name: Setting user id and group id facts
  ansible.builtin.set_fact:
    created_uid: "{{ ansible_facts.getent_passwd[navidrome_container_user].1 }}"
    created_gid: "{{ ansible_facts.getent_passwd[navidrome_container_user].2 }}"

- name: Ensure navidrome folders exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ navidrome_container_user }}"
    group: "{{ navidrome_container_user }}"
    state: directory
    mode: 0755
  loop:
    - "{{ navidrome_host_config_path }}"
    - "{{ navidrome_host_config_path }}/data"
    - "{{ navidrome_host_data_path }}/music"

- name: Copy navidrome docker-compose template.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ navidrome_host_config_path }}/docker-compose.yml"
    owner: "{{ navidrome_container_user }}"
    group: "{{ navidrome_container_user }}"
    mode: 0644
  become: true

- name: Create systemd navidrome service.
  ansible.builtin.template:
    src: templates/navidrome.service.j2
    dest: "/etc/systemd/system/navidrome.service"
    mode: 0644
  become: true

- name: Ensure navidrome.service is started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: navidrome
  become: true

- name: Check navidrome container
  ansible.builtin.uri:
    url: "http://localhost:{{ navidrome_host_port }}"
    status_code: [200, 401]
  register: result
  until: result.status == 200 or result.status == 401
  retries: 5
  delay: 30

- name: Remove old image versions
  become: true
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
  notify: Restart Docker service
